/**
 * Generated by scripts/content-dates.mjs — do not edit by hand.
 *
 * Per-project dates taken from the git history of content/projects.ts: the commit that
 * first introduced each project, and the last commit whose diff actually
 * changed that project's block. Feeds Article JSON-LD and sitemap lastmod,
 * so every date on the site is re-verifiable with `git log`.
 */
export type ContentDate = { published: string; updated: string };

export const CONTENT_DATES: Record<string, ContentDate> = {
  'hris-saas': {
    published: '2026-07-16',
    updated: '2026-08-29'
  },
  'ai-nail-platform': {
    published: '2026-07-16',
    updated: '2026-07-17'
  },
  'naily-app': {
    published: '2026-07-16',
    updated: '2026-07-18'
  },
  'naily-storefront': {
    published: '2026-07-17',
    updated: '2026-07-18'
  },
  'nkust-alumni': {
    published: '2026-07-16',
    updated: '2026-08-29'
  },
  'nkust-borrow': {
    published: '2026-07-16',
    updated: '2026-08-29'
  },
  'microservices-platform': {
    published: '2026-07-16',
    updated: '2026-07-17'
  },
  'retail-pos': {
    published: '2026-07-17',
    updated: '2026-07-17'
  },
  'b2b-wholesale-platform': {
    published: '2026-07-17',
    updated: '2026-07-17'
  },
  'field-sales-pwa': {
    published: '2026-07-17',
    updated: '2026-07-17'
  },
  'agm-evoting-system': {
    published: '2026-07-17',
    updated: '2026-07-17'
  },
  'ai-workflow': {
    published: '2026-07-16',
    updated: '2026-07-21'
  },
  ecobao: {
    published: '2026-07-21',
    updated: '2026-08-29'
  },
  'four-times-for-cook': {
    published: '2026-07-21',
    updated: '2026-08-29'
  },
  'helmet-detect': {
    published: '2026-08-29',
    updated: '2026-08-29'
  },
  'food-selector': {
    published: '2026-08-29',
    updated: '2026-08-29'
  }
};

/** Last change to any source that renders a given static route. */
export const ROUTE_DATES: Record<string, string> = {
  '': '2026-08-29',
  '/work': '2026-08-29',
  '/about': '2026-08-29',
  '/ai': '2026-08-29'
};
