import type { ToolNote } from './index';

/** Drawer C — "how it works" prose for the indexable tools in this drawer. */
export const DATA_NOTES: Record<string, ToolNote> = {
  'json-format': {
limits: [
      {
        zh: '所有數字都過了 JSON.parse,也就是都變成 IEEE 754 雙精度浮點。一個 19 位的雪花 ID 9007199254740993 格式化完會是 9007199254740992,而這裡不會警告你。輸出是 stringify 重新生成的,所以 1.0 會變成 1、1e3 會變成 1000。要原樣搬動這類欄位,就不要讓它過格式化這一手。',
        en: 'Every number round-trips through IEEE 754 doubles, so a 19-digit snowflake ID comes back changed, silently. Output is regenerated by stringify, so 1.0 becomes 1 and 1e3 becomes 1000.',
      },
      {
        zh: '重複鍵不算語法錯誤,所以輸出仍然照 JSON.parse 的規則只留最後一個——一份有兩個 "id" 的文件格式化完就是少一個欄位。差別在於它不再是無聲的:每一個重複的鍵會列出它在第幾行第幾字又出現一次,以及它在哪一個物件裡。代價是有效的輸入要多掃一次原文,一份 1 MB 的文件大約多三十毫秒。',
        en: 'A duplicate key is still not a syntax error, so the output keeps what JSON.parse keeps — the last one, one field short. What changed is the silence: every repeat is listed with its path, line and column. The cost is one extra scan of valid input, about 30 ms for a 1 MB document.',
      },
      {
        zh: '只認 JSON 本身,註解與尾逗號(JSONC、JSON5)一律當錯誤,因為這裡的工作是驗證而不是寬容。比較兩份 JSON 的差異請用 C05,從一大包裡撈欄位請用 C03。',
        en: 'Strict JSON only — comments and trailing commas are errors, not tolerated input. To compare two documents use C05; to pull fields out of one, C03.',
      },
    ],
  },
  'data-convert': {
limits: [
      {
        zh: '註解在轉換中一定消失,中介模型裡沒有註解這種東西。拿這裡整理一份寫滿說明的 config,回來會是一份乾淨但沒有註解的檔案。TOML 的日期時間讀得動,但落地成字串並附一條警告,原因同上。',
        en: 'Comments never survive — the intermediate model has no place for them, so a heavily annotated config comes back clean and undocumented. TOML dates parse but land as strings, with a warning.',
      },
      {
        zh: 'YAML 子集不做區塊純量(| 與 >),所以大部分 Kubernetes manifest 與任何把腳本塞進 YAML 的檔案會被明確拒收,而不是被讀成別的東西。讀錯一份 manifest 比讀不動更糟。要處理完整規格的 YAML,用本機的 yq 或 PyYAML。',
        en: 'No block scalars, which means most Kubernetes manifests are refused outright rather than misread. Misreading a manifest is worse than not reading it; for full-spec YAML, use yq or PyYAML locally.',
      },
      {
        zh: 'CSV 輸出的巢狀值會被壓成一行 JSON 塞進格子,那是這裡唯一不忠實的輸出。要瀏覽、排序或轉置一份 CSV 請用 C06,要先從大包 JSON 撈出該輸出的那個陣列請用 C03。輸入上限是 524,288 個字元,而不是 512 KB:檢查的是字串長度,那是 O(1) 的,而每按一次鍵都要重新解析一次,所以上限本身不能貴。同樣的字元數,全 ASCII 是 512 KB,全中文存成 UTF-8 大約是 1.5 MB——這就是訊息說字元不說 KB 的原因。',
        en: 'A nested value in CSV output is flattened into compact JSON inside the cell — the one place the output is not faithful. To browse or reshape a CSV use C06; to pick the array worth exporting out of a large payload, C03. Input is capped at 524,288 characters rather than at a byte count: checking string length is O(1) and the page reparses on every keystroke. The same length is 512 KB of ASCII but about 1.5 MB of UTF-8 Chinese, which is why the message counts characters.',
      },
    ],
  },
  'json-to-types': {
limits: [
      {
        zh: '命名是按結構去重的,所以形狀相同但語意不同的物件會共用一個型別名稱:{"from":{"lat":0,"lng":0},"to":{...}} 只會產出一個 interface From,to 也宣告成 From。這是刻意的取捨而不是還沒修——改成按鍵命名,一個在十個地方出現的形狀就會變成十份一模一樣的宣告,而那比共用名字更難讀。需要兩個名字就自己改,或分兩次貼。',
        en: 'Names are deduplicated by structure, so two same-shaped members share one declaration: {"from":{…},"to":{…}} yields one interface From, with to declared as From. Naming by key instead would emit one identical declaration per key, which reads worse; rename by hand when the two really are different types.',
      },
      {
        zh: '一份樣本只能證明它自己。哪個成員是 optional 完全取決於你貼進來的那幾筆剛好缺了什麼:貼一筆就會拿到一個全部必填的型別,貼十筆也只是十筆的聯集。要正確的界線,來源應該是 OpenAPI 或 protobuf 之類真正的契約,而不是一次回應。',
        en: 'A sample only proves things about itself. Which members are optional depends entirely on what the records you pasted happen to omit — one record yields an all-required type. For real boundaries, generate from a contract such as OpenAPI or protobuf.',
      },
      {
        zh: '整數與小數的判斷是猜的。JSON 裡的 1 沒有說自己是 int 還是剛好等於整數的 float,所以價格、比率、折扣這類欄位如果樣本剛好都是整數,Go 會拿到 int64、Pydantic 會拿到 int,那是錯的。這條警告只在 Zod、Go 與 Pydantic 的輸出上出現,因為那三個語言真的把猜測寫進宣告(.int()、int64、int),一個小數進來就會被擋下;TypeScript 的 number 不分整數與小數,輸出裡沒有這個猜測,所以不報——每份文件都亮著的警告等於沒有警告。另外數字在進來之前已經過了 JSON.parse,超過 2 的 53 次方的整數在推論看到它之前就變了(同 C01)。',
        en: 'Integer versus float is a guess: a price or ratio that happens to be whole in the sample becomes int64 in Go and int in Pydantic, which is wrong. The caveat is shown for Zod, Go and Pydantic, which commit to the guess in the declaration, and not for TypeScript, whose `number` holds either — a warning that never goes out says nothing. Numbers have also already passed through JSON.parse, so anything past 2^53 changed before inference saw it.',
      },
      {
        zh: '不產生 enum,也不從字串內容推 email、uuid、date-time 這類格式,因為一份樣本裡的三個值不足以證明那是全部的可能值。英文複數的單數化只認英文規則。推論有三個上限:64 層巢狀、任何一個物件合併完最多 5,000 個相異成員,以及整份樣本最多讀 100,000 個成員出現次數。兩個成員上限不是同一件事,因為成本不在讀而在合併:三千筆、每筆兩個欄位的陣列是六千次出現但只有兩個成員,那是這裡最常見的輸入;真正會慢的是每筆欄位都不一樣的陣列,合併的寬度就是那條 5,000。Zod 的輸出只是驗證的起點,真正的約束條件還是要自己補。',
        en: 'No enums, and no format inference for email, uuid or date-time — three values in one sample do not enumerate a domain. Depluralisation is English-only. Inference stops at 64 levels, at 5,000 distinct members in any one merged object (merging is what costs, and its cost is that width), and at 100,000 member occurrences read — a 3,000-record array of two-field objects is 6,000 occurrences and two members, and has to keep working. Zod output is a starting point; the real constraints still have to be written by hand.',
      },
    ],
  },
  'curl-convert': {
limits: [
      {
        zh: '讀不到本機檔案,這是瀏覽器的界線而不是懶。-d @body.json、-F avatar=@photo.png 與 -T 都指向本機路徑,產出的程式碼會留下一行註解和一個等你填的 file 變數,不會把檔案內容變出來。多部分表單的檔案欄位在 fetch 版本裡就是一個 form.append(name, file),那個 file 要你自己從 input 拿。',
        en: 'Local files are out of reach, which is the browser\'s boundary rather than an omission: -d @file, -F @file and -T leave a comment and a placeholder variable instead of file contents.',
      },
      {
        zh: '一次一條指令,分詞上限五千個單字。沒有對應寫法的旗標會被丟掉並列進警告,包括 --cert、--key、--resolve、--retry 這些;警告只會說某個旗標被丟了,不會說這段程式碼因此不能用——一個需要 TLS 客戶端憑證的請求轉出來會少掉憑證那一半,而它照樣看起來像能跑。',
        en: 'One command at a time, capped at 5,000 words. Flags with no code equivalent — --cert, --key, --resolve, --retry — are dropped and listed as warnings, so a request that needs a client certificate loses that half of itself.',
      },
      {
        zh: '只有這一個方向:curl 進、程式碼出,不做反向。要拆解一個 URL 的各段組成請用 J02,要查某個狀態碼或標頭的意思請用 D09,指令裡如果夾著一個 JWT,拆它請用 D03。',
        en: 'One direction only — curl in, code out, never the reverse. To take a URL apart use J02, for the meaning of a status code or header use D09, and for a JWT carried in the command, D03.',
      },
    ],
  },
};
