import type { ToolNote } from './index';

/** Drawer C — "how it works" prose for the indexable tools in this drawer. */
export const DATA_NOTES: Record<string, ToolNote> = {
  'json-format': {
    body: [
      {
        zh: '解析這件事交給瀏覽器內建的 JSON.parse。它是引擎用 C++ 實作的,比任何手寫的 JS 解析器快,而且它本身就是「什麼算合法 JSON」的定義;再寫一個只會多出一套判準。問題出在它拋出來的錯誤訊息:光 V8 就有兩種句型,只有其中一種帶位置(Expected property name ... at position 1,對上 Unexpected token \',\' ... is not valid JSON),Safari 與 Firefox 又各自講另一套話。就算真的拿到了位置,那是字元位移——在四百行的回應裡對著一個 2841,跟沒有位置差不多。',
        en: 'JSON.parse stays the parser: it is native, and it is the definition of valid JSON. Its errors are the problem — V8 alone has two message shapes, only one carrying a position, and a character offset is useless when you are looking at 400 lines.',
      },
      {
        zh: '所以這裡是兩段式。原生解析器先跑;只有在它失敗之後,另一支手寫的遞迴下降掃描器才啟動。掃描器不建任何資料結構,唯一任務是找出第一個錯在哪、那個位置原本期待什麼,然後把位移換算成從 1 起算的行與列,並把那一行原文引回來。代價是壞掉的輸入會被讀兩次,但輸入本來就已經壞了,而成功的那條路上一次都不多花。同一支掃描器還兼一件事:它在物件裡本來就逐個讀過鍵名,所以每個物件配一個 Set 就能認出重複的鍵。這一段跑在原生解析成功之後,因為重複鍵不是語法錯誤,是欄位會無聲消失。幾種常見死法有專門的說法:結尾多一個逗號會被指認成「這裡要的是值,不是尾逗號」,而不是含糊的 Unexpected token;字串裡有未跳脫的控制字元——直接把一行 log 貼進來最常撞到的就是這個;\\u 後面不足四位十六進位。掃描器是遞迴的,只跟得到 512 層;超過就停,而停在那裡的時候它不會把深度當成錯誤位置報出去——一份又深又壞的文件,真正的毛病幾乎不會剛好在第 512 層,報那個位置等於指錯地方,所以這種情況改交出引擎的原話並說明診斷停在哪。掃描器一路掃完覺得沒問題而原生解析器仍然拒收時,同樣是把引擎的原話交出來,不會因為自己找不到毛病就宣告文件沒事。行號是對著你貼進來的原文算的:前面有三行空白,錯誤還是報在它真正所在的那一行,不是少三行的那一行。',
        en: 'Two passes, then: the native parse first, and a hand-written recursive-descent scanner only after it fails, purely to locate the fault and name what was expected there. Trailing commas, raw control characters in strings and short \\u escapes get their own wording. Line numbers are counted in the text as pasted, and when the document is nested deeper than the scanner follows, the engine\'s message is handed over rather than the depth being blamed for the fault. When the scanner finds nothing but the engine still refuses, the engine\'s own message is shown rather than a clean bill of health.',
      },
      {
        zh: '排序鍵值是遞迴的,比較規則是 UTF-16 碼元順序——也就是 Array.prototype.sort 不給比較函式時的順序,C02 的資料格式轉換與 jq -S 都是這個順序。這裡原本用 localeCompare(\'en\'),換掉的理由是它依賴瀏覽器裡的 ICU 資料:同一份 JSON 在兩個瀏覽器、或在隔壁那件工具裡可能排出不同的鍵順序,而排序過的輸出就是拿去 diff 的。代價是大寫字母全部排在小寫之前(B 在 a 前面),那是碼元順序的樣子,換來的是同一份文件到哪裡都排成同一樣。陣列一律維持原順序:物件的鍵沒有順序語意,陣列有,把 [3,1,2] 排成 [1,2,3] 已經是改資料而不是排版。統計裡的巢狀深度只數容器,純量葉節點不多算一層,所以 {"a":1} 的深度是 1;大小欄位是 TextEncoder 編出來的 UTF-8 位元組數,不是字串長度,一份全中文的 JSON 這兩個數字差將近三倍。JSON Lines 輸出只在最外層是陣列時有意義,不是陣列就當成單一值輸出一行。',
        en: 'Key sorting recurses in UTF-16 code-unit order — the same rule as C02 and jq -S, chosen over localeCompare because collation depends on the browser\'s ICU data and sorted output exists to be diffed. Arrays never get reordered, because key order in an object carries no meaning and element order in an array does. Reported depth counts containers only, and size is UTF-8 bytes rather than string length.',
      },
    ],
    limits: [
      {
        zh: '所有數字都過了 JSON.parse,也就是都變成 IEEE 754 雙精度浮點。一個 19 位的雪花 ID 9007199254740993 格式化完會是 9007199254740992,而這裡不會警告你。輸出是 stringify 重新生成的,所以 1.0 會變成 1、1e3 會變成 1000。要原樣搬動這類欄位,就不要讓它過格式化這一手。',
        en: 'Every number round-trips through IEEE 754 doubles, so a 19-digit snowflake ID comes back changed, silently. Output is regenerated by stringify, so 1.0 becomes 1 and 1e3 becomes 1000.',
      },
      {
        zh: '重複鍵不算語法錯誤,所以輸出仍然照 JSON.parse 的規則只留最後一個——一份有兩個 "id" 的文件格式化完就是少一個欄位。差別在於它不再是無聲的:每一個重複的鍵會列出它在第幾行第幾字又出現一次,以及它在哪一個物件裡。代價是有效的輸入要多掃一次原文,一份 1 MB 的文件大約多三十毫秒。',
        en: 'A duplicate key is still not a syntax error, so the output keeps what JSON.parse keeps — the last one, one field short. What changed is the silence: every repeat is listed with its path, line and column. The cost is one extra scan of valid input, about 30 ms for a 1 MB document.',
      },
      {
        zh: '只認 JSON 本身,註解與尾逗號(JSONC、JSON5)一律當錯誤,因為這裡的工作是驗證而不是寬容。比較兩份 JSON 的差異請用 C05,從一大包裡撈欄位請用 C03。',
        en: 'Strict JSON only — comments and trailing commas are errors, not tolerated input. To compare two documents use C05; to pull fields out of one, C03.',
      },
    ],
  },
  'data-convert': {
    body: [
      {
        zh: '六種格式不是三十條轉換路徑,是十二段程式碼:每一種格式都解析成同一組 JSON 值,每一種格式都從那組值序列化出去。這個中介模型就是整件事最重要的取捨,因為它只認得 null、布林、數字、字串、清單與對應表——沒有日期、沒有註解、沒有錨點、沒有型別標籤。任何格式帶著超出這六種的資訊,過這一手都會掉。這件事寫在頁面上而不是藏著,因為使用者需要知道他拿回去的檔案少了什麼。',
        en: 'Six formats, twelve pieces of code rather than thirty conversion pairs: everything parses into one JSON value model and everything serializes back out of it. The model holds null, booleans, numbers, strings, lists and maps — no dates, comments, anchors or type tags — so whatever a format carries beyond those is lost in transit, and the UI says so.',
      },
      {
        zh: 'YAML 與 TOML 的解析器是手寫的子集,不是規格實作。一個符合 YAML 1.2 規格的解析器是五位數行的工程,假裝自己做到了才是真正的問題。所以這裡的規則反過來:子集外的構造一律拋錯,並指名是哪一個構造,而不是勉強讀成一個看起來合理但錯的結構。YAML 拒收錨點與別名、型別標籤、區塊純量、第二份文件、複合鍵、合併鍵與 tab 縮排;TOML 拒收三引號多行字串。同一層出現兩次的鍵、重複定義的表、TOML 的前導零整數,也都當錯誤處理。',
        en: 'The YAML and TOML parsers are hand-written subsets, not spec implementations — a conforming YAML parser is a five-figure line count and not something to fake. So anything outside the subset throws and names the construct it refused, rather than being read into something plausible and wrong.',
      },
      {
        zh: '純量的型別判斷刻意收窄。YAML 1.1 的 yes、no、on、off 在這裡一律留成字串,因為在那裡猜,就是挪威的國碼 NO 變成 false 的那個經典事故。反過來輸出的時候,這幾個字一定加引號——這個解析器不會把它們讀成布林,但下游可能是 PyYAML,而它會。同樣的謹慎用在整數上:YAML 裡超過 Number.isSafeInteger 範圍的整數留成字串,不去換一個精度掉了的數字回來;TOML 那邊直接拋錯,因為 TOML 的整數規格是 64 位,回一個少了尾數的值等於默默改資料。',
        en: 'Scalar typing stays narrow: YAML 1.1 spellings like yes, no and on remain strings, because guessing there is how the Norway country code becomes false. On the way out those same words are always quoted, since the downstream reader may well be PyYAML. Integers past the safe-integer range stay strings rather than coming back with precision gone.',
      },
      {
        zh: 'CSV 與 query string 是兩個裝不下任意樹狀結構的格式,所以它們的規則最多。CSV 輸出要求最外層是陣列,標題空白的欄位改叫 column_N、重複的標題加上欄號,欄位數對不上的列補空字串——這些都以警告回報而不是拋錯,因為解析確實成功了。query string 的方括號路徑先全部建成物件,第二輪才把鍵剛好是 0 到 n-1 的物件轉成陣列;一輪做完就得在只看到 a[0] 的時候猜 a 是清單還是一個鍵叫 "0" 的對應表。XML 這邊直接拒收 DOCTYPE 與實體宣告,只認五個預定義實體與數值參照——外部實體是這類解析器最常見的漏洞來源,不接就沒有這個問題。往回走的時候這條規則有個代價:{"a":{"0":"x"}} 寫成 a[0]=x,再讀回來就是 {"a":["x"]},因為括號寫法沒有辦法表達「一個鍵叫 0 的對應表」。這不是可以修的東西,是格式本身裝不下,所以改成轉換時明講:鍵剛好是 0 到 n-1 的物件會被指名,說它讀回來會變成陣列。鍵排序用的是 UTF-16 碼元順序,跟 C01 同一條規則,理由也一樣——排序過的輸出是拿去 diff 的,不該跟著瀏覽器的 ICU 資料變。所有鍵的寫入都走 Object.defineProperty,因為 obj["__proto__"] = v 會去改原型而不是新增屬性,那同時是一個鍵會消失的正確性 bug 和原型污染的標準形狀。',
        en: 'CSV and query strings cannot hold an arbitrary tree, so they carry the most rules — blank and duplicate CSV headers get renamed and reported as warnings, and bracket paths build objects first, turning 0..n-1 key sets into arrays only on a second pass — a map whose keys happen to be 0..n-1 therefore comes back as a list, which the conversion now names instead of leaving to be discovered. Key sorting is UTF-16 code-unit order, the same rule as C01. XML refuses DOCTYPE and entity declarations outright, and every key is written with defineProperty so __proto__ cannot reach the prototype chain.',
      },
    ],
    limits: [
      {
        zh: '註解在轉換中一定消失,中介模型裡沒有註解這種東西。拿這裡整理一份寫滿說明的 config,回來會是一份乾淨但沒有註解的檔案。TOML 的日期時間讀得動,但落地成字串並附一條警告,原因同上。',
        en: 'Comments never survive — the intermediate model has no place for them, so a heavily annotated config comes back clean and undocumented. TOML dates parse but land as strings, with a warning.',
      },
      {
        zh: 'YAML 子集不做區塊純量(| 與 >),所以大部分 Kubernetes manifest 與任何把腳本塞進 YAML 的檔案會被明確拒收,而不是被讀成別的東西。讀錯一份 manifest 比讀不動更糟。要處理完整規格的 YAML,用本機的 yq 或 PyYAML。',
        en: 'No block scalars, which means most Kubernetes manifests are refused outright rather than misread. Misreading a manifest is worse than not reading it; for full-spec YAML, use yq or PyYAML locally.',
      },
      {
        zh: 'CSV 輸出的巢狀值會被壓成一行 JSON 塞進格子,那是這裡唯一不忠實的輸出。要瀏覽、排序或轉置一份 CSV 請用 C06,要先從大包 JSON 撈出該輸出的那個陣列請用 C03。輸入上限是 524,288 個字元,而不是 512 KB:檢查的是字串長度,那是 O(1) 的,而每按一次鍵都要重新解析一次,所以上限本身不能貴。同樣的字元數,全 ASCII 是 512 KB,全中文存成 UTF-8 大約是 1.5 MB——這就是訊息說字元不說 KB 的原因。',
        en: 'A nested value in CSV output is flattened into compact JSON inside the cell — the one place the output is not faithful. To browse or reshape a CSV use C06; to pick the array worth exporting out of a large payload, C03. Input is capped at 524,288 characters rather than at a byte count: checking string length is O(1) and the page reparses on every keystroke. The same length is 512 KB of ASCII but about 1.5 MB of UTF-8 Chinese, which is why the message counts characters.',
      },
    ],
  },
  'json-to-types': {
    body: [
      {
        zh: '從樣本推型別本質上是猜,而這類工具出錯的地方幾乎都在猜的方式上。這裡守兩條規則。第一,陣列的元素是合併而不是取樣:第一筆有 note、第二筆沒有,note 就是 optional;只讀第一筆會產出一個拒收真實資料的型別,而那種型別上線之後才會炸。第二,不憑空補值——空陣列沒有辦法說出它裝什麼,一個在樣本裡永遠是 null 的成員也沒有辦法說出它有值的時候是什麼,這兩種情況一律輸出目標語言的「不知道」(unknown、any、Any),不會偷偷寫成 string。',
        en: 'Inferring a type from a sample is guessing, and this is where these tools usually go wrong. Array elements are merged rather than sampled, so a member missing from the second record comes out optional instead of required; and nothing is invented — an empty array and an always-null member both emit the target language\'s unknown, never string.',
      },
      {
        zh: '合併的定義是「同時接受兩邊的最小型別」。物件逐成員合併,任一邊缺的成員變成 optional;種類對不上就退成 union。兩個 union 相遇時會先按種類分組再合併同組,否則 {a:1} 與 {a:2} 會堆成 {a:number} | {a:number} 這種沒有人想要的宣告。數字分成整數與小數兩種,因為 Go 與 Python 非選一個不可,而 JSON 不告訴你答案:樣本裡的 1 會報成整數,同時掛一條警告,而不是安靜地在四個語言裡都變成浮點。空陣列、恆為 null、混型別 union、整數猜測這四種不確定各有一條警告顯示在頁面上。',
        en: 'A merge is the least type accepting both sides: objects merge member-wise, mismatched kinds collapse to a union, and two unions are grouped by kind first so {a:1} and {a:2} do not pile up as two identical object options. Numbers split into integer and fractional because Go and Python must choose and JSON does not say — a sample of 1 is reported as an integer with a warning attached.',
      },
      {
        zh: '命名是按結構去重的:同一個形狀只宣告一次名字,兩處長得一樣的物件不會變成兩個 interface。拆字用的是 Unicode 的字母與數字類別而不是 [A-Za-z0-9],所以一個中文鍵還是能產出可用的名字,而不是空字串——那會讓兩個不同的中文鍵撞成同一個名字。Go 那邊的欄位名走官方風格指南的縮寫表,user_id 出來是 UserID 不是 UserId;中文鍵在 Go 特別麻煩,因為導出的識別字必須以大寫字母開頭,而漢字沒有大小寫,所以它會加上 F 前綴,而不是安靜地生成一個未導出欄位——那種欄位 encoding/json 根本不會碰。宣告的順序是反過來輸出的,巢狀最深的先產生,倒過來排之後讀起來才跟原本的 JSON 同一個方向。',
        en: 'Names are deduplicated by structure, so one shape is declared once. Word splitting uses Unicode letter and number classes, so a Chinese key still yields a distinct usable name. Go field names follow the initialism list — user_id becomes UserID — and a CJK key gets an F prefix, because an exported Go identifier must begin with an upper-case letter and an unexported field is invisible to encoding/json.',
      },
      {
        zh: '四種輸出的差異是跟著語言走的,不是換皮。TypeScript 的 unknown 本來就容納 null,所以不會再多加一個 | null。Go 沒有值得生成的和型別,union 一律落成 any——那是誠實的寫法,假裝生一個 interface 出來只是把問題往後推;可為 null 的純量變成指標型別 *string,切片與 any 不加,optional 則是 json tag 上的 omitempty,縮排用 tab 並把欄位對齊,跟 gofmt 一樣。Pydantic 這邊,鍵只要不是合法的 Python 識別字或撞到保留字,就會改名並補 alias,而只要出現任何 alias,類別就會帶上 model_config = ConfigDict(populate_by_name=True),否則用屬性名建構這個 model 會失敗。',
        en: 'The four emitters diverge where the languages do. TypeScript skips a redundant | null next to unknown. Go renders a union as any — there is no sum type worth generating — puts nullable scalars behind a pointer, uses omitempty and tab-aligned fields like gofmt. Pydantic renames keys that are not valid Python identifiers and adds an alias, plus ConfigDict(populate_by_name=True) on any class that needed one.',
      },
    ],
    limits: [
      {
        zh: '命名是按結構去重的,所以形狀相同但語意不同的物件會共用一個型別名稱:{"from":{"lat":0,"lng":0},"to":{...}} 只會產出一個 interface From,to 也宣告成 From。這是刻意的取捨而不是還沒修——改成按鍵命名,一個在十個地方出現的形狀就會變成十份一模一樣的宣告,而那比共用名字更難讀。需要兩個名字就自己改,或分兩次貼。',
        en: 'Names are deduplicated by structure, so two same-shaped members share one declaration: {"from":{…},"to":{…}} yields one interface From, with to declared as From. Naming by key instead would emit one identical declaration per key, which reads worse; rename by hand when the two really are different types.',
      },
      {
        zh: '一份樣本只能證明它自己。哪個成員是 optional 完全取決於你貼進來的那幾筆剛好缺了什麼:貼一筆就會拿到一個全部必填的型別,貼十筆也只是十筆的聯集。要正確的界線,來源應該是 OpenAPI 或 protobuf 之類真正的契約,而不是一次回應。',
        en: 'A sample only proves things about itself. Which members are optional depends entirely on what the records you pasted happen to omit — one record yields an all-required type. For real boundaries, generate from a contract such as OpenAPI or protobuf.',
      },
      {
        zh: '整數與小數的判斷是猜的。JSON 裡的 1 沒有說自己是 int 還是剛好等於整數的 float,所以價格、比率、折扣這類欄位如果樣本剛好都是整數,Go 會拿到 int64、Pydantic 會拿到 int,那是錯的。這條警告只在 Zod、Go 與 Pydantic 的輸出上出現,因為那三個語言真的把猜測寫進宣告(.int()、int64、int),一個小數進來就會被擋下;TypeScript 的 number 不分整數與小數,輸出裡沒有這個猜測,所以不報——每份文件都亮著的警告等於沒有警告。另外數字在進來之前已經過了 JSON.parse,超過 2 的 53 次方的整數在推論看到它之前就變了(同 C01)。',
        en: 'Integer versus float is a guess: a price or ratio that happens to be whole in the sample becomes int64 in Go and int in Pydantic, which is wrong. The caveat is shown for Zod, Go and Pydantic, which commit to the guess in the declaration, and not for TypeScript, whose `number` holds either — a warning that never goes out says nothing. Numbers have also already passed through JSON.parse, so anything past 2^53 changed before inference saw it.',
      },
      {
        zh: '不產生 enum,也不從字串內容推 email、uuid、date-time 這類格式,因為一份樣本裡的三個值不足以證明那是全部的可能值。英文複數的單數化只認英文規則。推論有三個上限:64 層巢狀、任何一個物件合併完最多 5,000 個相異成員,以及整份樣本最多讀 100,000 個成員出現次數。兩個成員上限不是同一件事,因為成本不在讀而在合併:三千筆、每筆兩個欄位的陣列是六千次出現但只有兩個成員,那是這裡最常見的輸入;真正會慢的是每筆欄位都不一樣的陣列,合併的寬度就是那條 5,000。Zod 的輸出只是驗證的起點,真正的約束條件還是要自己補。',
        en: 'No enums, and no format inference for email, uuid or date-time — three values in one sample do not enumerate a domain. Depluralisation is English-only. Inference stops at 64 levels, at 5,000 distinct members in any one merged object (merging is what costs, and its cost is that width), and at 100,000 member occurrences read — a 3,000-record array of two-field objects is 6,000 occurrences and two members, and has to keep working. Zod output is a starting point; the real constraints still have to be written by hand.',
      },
    ],
  },
  'curl-convert': {
    body: [
      {
        zh: '這類轉換器壞掉的地方幾乎都在 shell 引號上,所以這裡分成兩層:先有一個分詞器,把命令列按 shell 的規則切成單字;然後才是旗標解析器,在切好的單字上跑。分詞器實作的是 curl 指令實際會用到的那一部分——單引號內完全字面、雙引號內反斜線只對 " \\ $ 與反引號這四個字元有效、反斜線接換行是續行、$\'...\' 的 ANSI-C 字串含 \\xNN。引號沒收尾一律當錯誤,不會默默把後面的內容丟掉:那種處理會產出一段看起來正確、但送出去的 body 是錯的程式碼,而這是最難察覺的一種壞法。碰到管線、分號或 & 就停,後面那些是另一個程式的事——但一定會留一條警告。curl http://x/?a=1&b=2 沒加引號時,shell 本來就會在 & 把指令切斷,而貼上來的指令很常是這樣:產出的程式碼會去打一個少了半截 query 的網址,而它看起來完全正常。所以被切掉的位置、切掉的內容、以及「把整個 URL 用引號包起來」都寫在警告裡。',
        en: 'Shell quoting is where these converters break, so there are two layers: a tokenizer covering the POSIX word-splitting curl commands actually use — literal single quotes, the four-character backslash set inside double quotes, line continuations, $\'...\' strings — and a flag parser over the resulting words. An unclosed quote is an error, because silently dropping the rest of the command yields code that looks right and sends the wrong body. A pipe, semicolon or unquoted `&` ends the command the way a shell would — and is reported, since `curl http://x?a=1&b=2` unquoted otherwise produces code that requests half a query string.',
      },
      {
        zh: '沒有任何東西被求值。$(date)、${TOKEN} 與反引號都以原樣的文字留在字串裡,並附一條警告說明產出的程式碼會真的把那幾個錢字號送出去,而不是你 shell 裡的值。旗標解析這一層有幾個必須處理的現實:-sL 這種併寫的短旗標會被展開、-XPOST 與 -H\'Accept: x\' 這種值黏在旗標後面的寫法要切開、--header=x 的等號形式也要認。有一整張表列的是「吃一個參數但我們不用」的旗標,例如 -o、--retry、--cert:列出來的目的不是支援它們,而是讓它們的參數不要被誤認成 URL——那會產出一段打錯目標的程式碼。這些旗標每被丟掉一個都會出現在警告裡。',
        en: 'Nothing is evaluated: $(...), ${...} and backticks survive as literal text, with a warning saying the generated code will send the dollar signs rather than whatever the shell would have substituted. The flag parser expands bundled short flags, splits values glued to a flag, and keeps an explicit list of value-taking flags it ignores, so their arguments are not mistaken for the URL.',
      },
      {
        zh: '輸出的目標是忠實而不是漂亮。curl 的 -d 不管你有沒有要求都會送 application/x-www-form-urlencoded,所以產出的程式碼會把這個標頭明寫出來,而不是讓讀者去繼承一個看不見的預設值;--json 同時補上 Content-Type 與 Accept;方法也是照 curl 的規則推的,-I 是 HEAD、沒有 body 是 GET、有 body 是 POST,-G 則把 -d 的內容搬進 query string 並清空 body。Basic 認證在 fetch 的輸出裡刻意留成 btoa(\'user:pass\') 而不是預先算好的 base64 常數:一個 base64 常數會把裡面是哪組帳密藏起來,而這段程式碼很可能被貼到別人看得到的地方。',
        en: 'The emitters aim at faithful rather than tidy. curl -d sends x-www-form-urlencoded whether or not you asked, so the header is written out explicitly instead of inherited invisibly; --json adds both Content-Type and Accept; -G moves the data into the query string. Basic auth stays as btoa(\'user:pass\') on purpose, because a precomputed base64 constant hides which credentials are inside it.',
      },
      {
        zh: '有些事目標語言真的做不到,那就寫在註解裡,不安靜地刪掉。--insecure 在瀏覽器的 fetch 沒有對應寫法,因為瀏覽器一定驗證憑證,沒有開關可以關;--proxy 在 fetch 也只能留註解。axios 則相反,它有 proxy 設定,所以 -x http://host:8080 會產出 protocol、host、port(指令裡沒寫 port 就用 curl 記載的預設值 1080),帳密走 proxy 自己的 auth,並附一行說明只有 Node 上的 axios 會理它、瀏覽器不會。反過來 requests 有一個相反方向的落差:它預設對所有方法跟隨轉址,而 curl 沒有 -L 時一個都不跟,所以產出的 Python 會附一行註解告訴你要補 allow_redirects=False 才等價——沉默的行為差異比少一個參數更貴。httpie 的輸出走的是 request item 而不是引號包住的 body:JSON 物件拆成 key=value 與 key:=json,已經百分比編碼過的表單值會先解回純文字(httpie 自己會編碼),而真正的原始位元組只能用 echo ... | http 從標準輸入送進去。',
        en: 'Where a target genuinely cannot express something, a comment says so instead of dropping it: --insecure has no fetch equivalent because a browser always verifies. --proxy is a comment in fetch but real configuration in axios — protocol, host and port, with curl\'s default port of 1080 when the command omits it, and a note that only axios on Node honours it. The gap also runs the other way — requests follows redirects by default for every method while curl follows none without -L, so the Python output tells you to pass allow_redirects=False. httpie output uses request items, with raw bodies piped in on stdin.',
      },
    ],
    limits: [
      {
        zh: '讀不到本機檔案,這是瀏覽器的界線而不是懶。-d @body.json、-F avatar=@photo.png 與 -T 都指向本機路徑,產出的程式碼會留下一行註解和一個等你填的 file 變數,不會把檔案內容變出來。多部分表單的檔案欄位在 fetch 版本裡就是一個 form.append(name, file),那個 file 要你自己從 input 拿。',
        en: 'Local files are out of reach, which is the browser\'s boundary rather than an omission: -d @file, -F @file and -T leave a comment and a placeholder variable instead of file contents.',
      },
      {
        zh: '一次一條指令,分詞上限五千個單字。沒有對應寫法的旗標會被丟掉並列進警告,包括 --cert、--key、--resolve、--retry 這些;警告只會說某個旗標被丟了,不會說這段程式碼因此不能用——一個需要 TLS 客戶端憑證的請求轉出來會少掉憑證那一半,而它照樣看起來像能跑。',
        en: 'One command at a time, capped at 5,000 words. Flags with no code equivalent — --cert, --key, --resolve, --retry — are dropped and listed as warnings, so a request that needs a client certificate loses that half of itself.',
      },
      {
        zh: '只有這一個方向:curl 進、程式碼出,不做反向。要拆解一個 URL 的各段組成請用 J02,要查某個狀態碼或標頭的意思請用 D09,指令裡如果夾著一個 JWT,拆它請用 D03。',
        en: 'One direction only — curl in, code out, never the reverse. To take a URL apart use J02, for the meaning of a status code or header use D09, and for a JWT carried in the command, D03.',
      },
    ],
  },
};
