/**
 * Derives per-project published / updated dates from git history.
 *
 * Why not `new Date()` at build time: stamping every URL with the build
 * timestamp is noise search engines learn to distrust. Why not hand-typed
 * dates: they rot. This walks every commit that touched the content module,
 * extracts each project's own block, and records the commit dates where that
 * block actually changed — so `datePublished` / `dateModified` / sitemap
 * `lastmod` are all independently re-verifiable from `git log`.
 *
 * Usage: node scripts/content-dates.mjs          # print
 *        node scripts/content-dates.mjs --write  # write content/dates.ts
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const FILE = 'content/projects.ts';
const git = (...args) =>
  execFileSync('git', args, { encoding: 'utf8', maxBuffer: 64 << 20 });

/** Split a projects.ts source into { slug: blockText }. */
function blocks(src) {
  const out = {};
  const re = /\n {2}\{\n {4}slug: '([^']+)'/g;
  const marks = [];
  let m;
  while ((m = re.exec(src))) marks.push({ slug: m[1], start: m.index });
  marks.forEach((mark, i) => {
    const end = i + 1 < marks.length ? marks[i + 1].start : src.length;
    out[mark.slug] = src.slice(mark.start, end);
  });
  return out;
}

// Oldest → newest commits that touched the content module.
const commits = git(
  'log',
  '--reverse',
  '--format=%H %ad',
  '--date=short',
  '--',
  FILE,
)
  .trim()
  .split('\n')
  .map((line) => {
    const [hash, date] = line.split(' ');
    return { hash, date };
  });

const dates = {};
let prev = {};
for (const { hash, date } of commits) {
  let src = '';
  try {
    src = git('show', `${hash}:${FILE}`);
  } catch {
    continue; // file did not exist at this commit
  }
  const now = blocks(src);
  for (const [slug, text] of Object.entries(now)) {
    if (!(slug in prev)) {
      dates[slug] = { published: date, updated: date };
    } else if (prev[slug] !== text) {
      dates[slug].updated = date;
    }
  }
  prev = now;
}

// Slugs that were removed from the module keep showing up in old commits.
const live = Object.keys(blocks(git('show', `HEAD:${FILE}`)));
const current = Object.fromEntries(live.map((slug) => [slug, dates[slug]]));

/**
 * Static routes get their lastmod from the newest commit touching any source
 * that actually renders them — content module, copy, or the page itself.
 */
const ROUTE_SOURCES = {
  '': ['messages', 'src/app/[locale]/page.tsx', 'src/components/deck', 'src/styles/projector.css', 'content'],
  '/work': [FILE, 'messages', 'src/app/[locale]/work/page.tsx'],
  '/about': [
    'content/experience.ts',
    'messages',
    'src/app/[locale]/about/page.tsx',
  ],
  '/ai': ['content/agentic.ts', 'messages', 'src/app/[locale]/ai/page.tsx'],
};
const routes = Object.fromEntries(
  Object.entries(ROUTE_SOURCES).map(([route, paths]) => [
    route,
    git('log', '-1', '--format=%ad', '--date=short', '--', ...paths).trim(),
  ]),
);

/** JSON.stringify, re-quoted to match the repo's single-quote style. */
const ts = (value) =>
  JSON.stringify(value, null, 2)
    .replace(/"/g, "'")
    // quote only the keys that need it (slugs contain '-', routes '/')
    .replace(/^(\s*)'([A-Za-z_$][\w$]*)':/gm, "$1$2:");

const out =
  `/**\n` +
  ` * Generated by scripts/content-dates.mjs — do not edit by hand.\n` +
  ` *\n` +
  ` * Per-project dates taken from the git history of ${FILE}: the commit that\n` +
  ` * first introduced each project, and the last commit whose diff actually\n` +
  ` * changed that project's block. Feeds Article JSON-LD and sitemap lastmod,\n` +
  ` * so every date on the site is re-verifiable with \`git log\`.\n` +
  ` */\n` +
  `export type ContentDate = { published: string; updated: string };\n\n` +
  `export const CONTENT_DATES: Record<string, ContentDate> = ${ts(current)};\n\n` +
  `/** Last change to any source that renders a given static route. */\n` +
  `export const ROUTE_DATES: Record<string, string> = ${ts(routes)};\n`;

if (process.argv.includes('--write')) {
  writeFileSync('content/dates.ts', out);
  console.error(`content/dates.ts — ${live.length} projects`);
} else {
  process.stdout.write(out);
}
