/* Generated by scripts/gen-tool-loader.mjs — do not edit by hand. */

/** Slugs with an implementation on disk, in registry order. */
export const BUILT_TOOLS: readonly string[] = [

];

export const BUILT = new Set(BUILT_TOOLS);
